  # Workflow to automate fork alerts if forks are created within personal accounts 
name: Fork Issue Alert 
on: fork 
jobs:
  alert: 
    name: Create Alert Issue 
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/fork-issue-template.md
    if: github.event.forkee.owner.type != 'Organization'
